import {
    sqliteTable,
    text,
    integer,
    index,
    uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { users } from "@/features/auth/server/schema";
import { type InferSelectModel, sql } from "drizzle-orm";

// Ledger（账本）
export const ledgers = sqliteTable("ledgers", {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    userId: text("user_id")
        .notNull()
        .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    metadata: text("metadata", { mode: "json" }).$type<LedgerMetadata>().default({}),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    deletedAt: integer("deleted_at", { mode: "timestamp_ms" }),
}, (table) => [
    index("idx_ledgers_user_id").on(table.userId),
]);

export interface LedgerMetadata {
    settings?: {
        aiLanguage?: string;
        currencies?: string[];
        mainCurrency?: string;
        collapseProcessingDefault?: boolean;
        collapseBillsDefault?: boolean;
        aiCustomPrompt?: string;
        // Future expansion
        showCentsOnDashboard?: boolean;
        themeColor?: string;
    };
    aiConfig?: {
        modelPreference?: string;
    };
}

export type Ledger = InferSelectModel<typeof ledgers>;

// EntryCategory（分录分类）
export const entryCategories = sqliteTable("entry_categories", {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    ledgerId: text("ledger_id")
        .notNull()
        .references(() => ledgers.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    icon: text("icon"),
    sortOrder: integer("sort_order").notNull().default(0),
    isEditable: integer("is_editable", { mode: "boolean" }).notNull().default(true),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    deletedAt: integer("deleted_at", { mode: "timestamp_ms" }),
}, (table) => [
    uniqueIndex("uniq_category_name_per_ledger").on(table.ledgerId, table.name).where(sql`${table.deletedAt} IS NULL`),
]);

export type EntryCategory = InferSelectModel<typeof entryCategories>;

// sourceDocuments is imported safely
import { sourceDocuments } from "@/features/source-document/server/schema";

// LedgerEntry（账目分录）
export const ledgerEntries = sqliteTable("ledger_entries", {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    ledgerId: text("ledger_id")
        .notNull()
        .references(() => ledgers.id, { onDelete: "cascade" }),
    categoryId: text("category_id").references(() => entryCategories.id, {
        onDelete: "set null",
    }),
    sourceDocumentId: text("source_document_id").references(() => sourceDocuments.id, {
        onDelete: "set null",
    }),
    amount: text("amount").notNull(), // SQLite has no decimal, use text
    currency: text("currency"),
    itemName: text("item_name").notNull(),
    description: text("description"),
    entryDate: text("entry_date"), // yyyy-MM-dd format, no timezone ambiguity
    convertedAmount: text("converted_amount"), // Amount in ledger's main currency
    exchangeRate: text("exchange_rate"), // Exchange rate used for conversion
    metadata: text("metadata", { mode: "json" }).$type<LedgerEntryMetadata>().default({}),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    deletedAt: integer("deleted_at", { mode: "timestamp_ms" }),
}, (table) => [
    index("idx_ledger_entries_ledger_date").on(table.ledgerId, table.entryDate),
    index("idx_ledger_entries_source_doc").on(table.sourceDocumentId),
    index("idx_ledger_entries_created_at").on(table.createdAt),
    // Optimization for category filtering with date sort
    index("idx_ledger_entries_category_date").on(table.ledgerId, table.categoryId, table.entryDate),
    // Optimization for default sort (createdAt) within a ledger
    index("idx_ledger_entries_ledger_created").on(table.ledgerId, table.createdAt),
]);

export interface LedgerEntryMetadata {
    aiReasoning?: {
        confidenceScore?: number;
        logicTrace?: string;
        isAutoGenerated?: boolean;
    };
    externalReference?: {
        systemName?: string;
        transactionId?: string;
    };
    tags?: string[];
}

export type LedgerEntry = InferSelectModel<typeof ledgerEntries>;

// ServiceCredentials (服务凭据)
export const serviceCredentials = sqliteTable("service_credentials", {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    key: text("key").notNull().unique(),
    ledgerId: text("ledger_id")
        .notNull()
        .references(() => ledgers.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
    lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
    deletedAt: integer("deleted_at", { mode: "timestamp_ms" }),
});

export type ServiceCredential = InferSelectModel<typeof serviceCredentials>;
