import {
    pgTable,
    uuid,
    text,
    timestamp,
    boolean,
    integer,
    decimal,
    date,
    jsonb,
    index,

    uniqueIndex,
} from "drizzle-orm/pg-core";
import { users } from "@/features/auth/server/schema";
import { type InferSelectModel, sql } from "drizzle-orm";

// Ledger（账本）
export const ledgers = pgTable("ledgers", {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
        .notNull()
        .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    metadata: jsonb("metadata").$type<LedgerMetadata>().default({}),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
    deletedAt: timestamp("deleted_at"),
}, (table) => [
    index("idx_ledgers_user_id").on(table.userId),
]);

export interface LedgerMetadata {
    settings?: {
        aiLanguage?: string;
        currencies?: string[];
        mainCurrency?: string;
        autoRecognizeDate?: boolean;
        collapseProcessingDefault?: boolean;
        collapseBillsDefault?: boolean;
        aiCustomPrompt?: string;
        // Future expansion
        showCentsOnDashboard?: boolean;
        themeColor?: string;
    };
    aiConfig?: {
        modelPreference?: string;
    };
}

export type Ledger = InferSelectModel<typeof ledgers>;

// EntryCategory（分录分类）
export const entryCategories = pgTable("entry_categories", {
    id: uuid("id").primaryKey().defaultRandom(),
    ledgerId: uuid("ledger_id")
        .notNull()
        .references(() => ledgers.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    description: text("description"),
    icon: text("icon"),
    sortOrder: integer("sort_order").notNull().default(0),
    isEditable: boolean("is_editable").notNull().default(true),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
    deletedAt: timestamp("deleted_at"),
}, (table) => [
    uniqueIndex("uniq_category_name_per_ledger").on(table.ledgerId, table.name).where(sql`${table.deletedAt} IS NULL`),
]);

export type EntryCategory = InferSelectModel<typeof entryCategories>;

// Note: LedgerEntries depends on SourceDocuments, but SourceDocuments depends on Ledgers
// We need to verify if we can import SourceDocuments from legacy here.
// But legacy imports ledgers. 
// If we import sourceDocuments here, legacy imports ledgers -> cycle.
// However, LedgerEntries NEEDS SourceDocumentId.
// We can use a workaround: defined the column but referencing lazily?
// Drizzle references are lazy functions: references(() => sourceDocuments.id)
// So we can import sourceDocuments from legacy.ts.
// legacy.ts imports ledgers from here.
// Is this safe?
// legacy.ts is NOT created yet.
// let's create the file assuming the import will work.

// We will add the import at the top after creating legacy.ts logic.
// For now, I'll comment out the reference or assume I can import it.
// Actually, I can decouple it? No, FK existence is important for migrations.
// I will import `sourceDocuments` from "@/lib/db/schemas/legacy".

import { sourceDocuments } from "@/features/source-document/server/schema";

// LedgerEntry（账目分录）
export const ledgerEntries = pgTable("ledger_entries", {
    id: uuid("id").primaryKey().defaultRandom(),
    ledgerId: uuid("ledger_id")
        .notNull()
        .references(() => ledgers.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id").references(() => entryCategories.id, {
        onDelete: "set null",
    }),
    sourceDocumentId: uuid("source_document_id").references(() => sourceDocuments.id, {
        onDelete: "set null",
    }),
    amount: decimal("amount", { precision: 12, scale: 2 }).notNull(),
    currency: text("currency"),
    itemName: text("item_name").notNull(),
    description: text("description"),
    entryDate: date("entry_date", { mode: "date" }),
    metadata: jsonb("metadata").$type<LedgerEntryMetadata>().default({}),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    deletedAt: timestamp("deleted_at"),
}, (table) => [
    index("idx_ledger_entries_ledger_date").on(table.ledgerId, table.entryDate),
    index("idx_ledger_entries_source_doc").on(table.sourceDocumentId),
    index("idx_ledger_entries_created_at").on(table.createdAt),
    // Optimization for category filtering with date sort
    index("idx_ledger_entries_category_date").on(table.ledgerId, table.categoryId, table.entryDate),
    // Optimization for default sort (createdAt) within a ledger
    index("idx_ledger_entries_ledger_created").on(table.ledgerId, table.createdAt),
]);

export interface LedgerEntryMetadata {
    aiReasoning?: {
        confidenceScore?: number;
        logicTrace?: string;
        isAutoGenerated?: boolean;
    };
    externalReference?: {
        systemName?: string;
        transactionId?: string;
    };
    tags?: string[];
}

export type LedgerEntry = InferSelectModel<typeof ledgerEntries>;

// ServiceCredentials (服务凭据)
export const serviceCredentials = pgTable("service_credentials", {
    id: uuid("id").primaryKey().defaultRandom(),
    key: text("key").notNull().unique(),
    ledgerId: uuid("ledger_id")
        .notNull()
        .references(() => ledgers.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    lastUsedAt: timestamp("last_used_at"),
    deletedAt: timestamp("deleted_at"),
});

export type ServiceCredential = InferSelectModel<typeof serviceCredentials>;
